---
- name: Create an EPG
  hosts: all
  connection: ssh
  gather_facts: no
  vars_files: 
    - vars.yml

  tasks:

  - name: Create an EPG
    aci_epg:
      host: 10.99.9.1
      username: igorhenrique
      password: ansible123
      tenant: "{{ tenant }}"
      description: "{{ description }}"
      ap: "{{ ap }}"
      epg: "{{ epg }}"
      bd: "{{ bd }}"
      preferred_group: yes
      state: present
      validate_certs: false
    delegate_to: localhost
