---
- name: Create Leaf Profile
  hosts: all
  connection: ssh
  gather_facts: no
  vars_files: ./vars.yml

  tasks:

  - name: Create Leaf Profile (SwProf)
    aci_switch_policy_leaf_profile:
      host: "{{ host }}"
      username: "{{ user }}"
      password: "{{ pass }}"
      leaf_profile: "n9k-lf1-{{ site_id }}-{{ sw_id }}-SwProf"
      state: present
      validate_certs: false



