---
- name: Create Leaf Profile
  hosts: all
  connection: ssh
  gather_facts: no
  vars_files: ./vars.yml

  tasks:

  - name: Add a switch policy leaf profile selector associated Node Block Range
    aci_switch_leaf_selector:
      host: "{{ host }}"
      username: "{{ user }}"
      password: "{{ pass }}"
      leaf_profile: "n9k-lf1-{{ site_id }}-{{ sw_id }}-SwProf"
      leaf: "n9k-lf1-{{ site_id }}-{{ sw_id }}-IntProf"
      leaf_node_blk: "LEAF_{{ sw_id }}"
      from: "{{ sw_id }}"
      to: "{{ sw_id }}"
      state: present
      validate_certs: false





