---
- name: Create Leaf Profile
  hosts: all
  connection: ssh
  gather_facts: no
  vars_files: ./vars.yml

  tasks:

  - name: Query Data about given Leaf 
    aci_switch_policy_leaf_profile:
      host: "{{ host }}"
      username: "{{ user }}"
      password: "{{ pass }}"
      leaf_profile: "n9k-lf1-{{ site_id }}-{{ sw_id }}-SwProf"
      state: query
      validate_certs: false
    register: query_result

  - copy:
      content: "{{ query_result }}"
      dest: sw_query.json
    delegate_to: localhost

