---
- name: Query Bridge Domains from a Tenant
  hosts: all
  connection: ssh
  gather_facts: no
  vars_files: 
    - vars.yml

  tasks:
  - name: Query BDs from a Tenant
    aci_bd:
      host: 10.99.9.1
      username: igorhenrique
      password: ansible123
      validate_certs: no
      tenant: "{{ tenant }}"
      state: query
    register: bds

  - copy:
      content: "{{ bds }}"
      dest: ../querys/aci_bds.json
    delegate_to: localhost
