---
- name: Query VRFs
  hosts: all
  connection: ssh
  gather_facts: no
  vars_files: 
    - vars.yml

  tasks:
  - name: Query VRFs from ACI
    aci_vrf:
      host: 10.99.9.1
      username: igorhenrique
      password: ansible123
      tenant: "{{ tenant }}"
      state: query
      validate_certs: false
    delegate_to: localhost
    register: vrf


  - copy:
      content: "{{ vrf.current }}"
      dest: ../querys/aci_vrfs.json
    delegate_to: localhost