---
- name: Create a Domain
  hosts: all
  connection: ssh
  gather_facts: no
  vars_files: ./vars.yml

  tasks:

  - name: Create a Domain
    aci_domain:
      host: "{{ host }}"
      username: "{{ user }}"
      password: "{{ pass }}"
      domain: "{{ domain }}"
      domain_type: phys
      state: present
      validate_certs: false
    register: query_result
	
	