---
- name: Create a Tenant
  hosts: all
  connection: ssh
  gather_facts: no
  vars_files: ./vars.yml

  tasks:

  - name: Create a Tenant
    aci_tenant:
      host: "{{ host }}"
      username: "{{ user }}"
      password: "{{ pass }}"
      tenant: "{{ tenant }}"
      description: "{{ tenant_descr }}":
      state: present
      validate_certs: false
    register: query_result