---
- hosts: local
  vars_files:
    - ./variaveisVars.yml
  tasks:
  - aci_ap:
      hostname: "{{ host }}"
      username: "{{ user }}"
      password: "{{ pass }}"
      tenant: "{{ tenant }}"
      validate_certs: no
      description: Aplicattion proffile Maidana
      state: present
      ap: "{{ ap }}"
