---

- name: Create Tenant for Combo 1
  hosts: all
  connection: ssh
  gather_facts: no
  vars_files: vars_combo1.yml

  tasks:

  - name: Create a Tenant
    aci_tenant:
      host: "{{ host }}"
      username: "{{ user }}"
      password: "{{ pass }}"
      tenant: "{{ tenant }}"
      description: "{{ tenant_descr }}"
      state: present
      validate_certs: false
    register: combo1

- name: Create Object inside Tenant for Combo 1
  hosts: all
  connection: ssh
  gather_facts: no
  vars_files: vars_combo1.yml

  tasks:

  - aci_ap:
      hostname: "{{ host }}"
      username: "{{ user }}"
      password: "{{ pass }}"
      tenant: "{{ tenant }}"
      validate_certs: no
      description: "{{ ap_descr }}"
      state: present
      ap: "{{ ap }}"

  - aci_vrf:
      hostname: "{{ host }}"
      username: "{{ user }}"
      password: "{{ pass }}"
      tenant: "{{ tenant }}"
      description: "{{ vrf_descr}}"
      policy_control_preference: enforced
      policy_control_direction: ingress
      state: present
      validate_certs: no
      vrf: "{{ vrf }}"

  - aci_bd:
      hostname: "{{ host }}"
      username: "{{ user }}"
      password: "{{ pass }}"
      validate_certs: false
      description: "{{ bd_descr }}"
      state: present
      tenant: "{{ tenant }}"
      vrf: "{{ vrf }}"
      l2_unknown_unicast: flood
      arp_flooding: true
      bd: "{{ bd }}"

  - aci_epg:
      hostname: "{{ host }}"
      username: "{{ user }}"
      password: "{{ pass }}"
      tenant: "{{ tenant }}"
      ap: "{{ ap }}"
      description: "{{ epg_descr }}"
      bd: "{{ bd }}"
      preferred_group: no
      state: present
      validate_certs: no
      epg: "{{ epg }}"
