---
- name: Create a Bridge Domain
  hosts: all
  connection: ssh
  gather_facts: no
  vars_files: ./vars.yml

  tasks:

  - name: Create a BD
    aci_bd:
      host: "{{ apic }}"
      username: "{{ user }}"
      password: "{{ pass }}"
      tenant: "{{ tenant }}"
      vrf: "{{ vrf }}"
      bd: "{{ bd }}"
      state: present
      validate_certs: false
    delegate_to: localhost
