---
- name: Create a VRF
  hosts: all
  connection: ssh
  gather_facts: no
  vars_files: ./vars.yml

  tasks:

  - name: Create a VRF
    aci_vrf:
      host: "{{ host }}"
      username: "{{ user }}"
      password: "{{ pass }}"
      tenant: "{{ tenant }}"
      vrf: "{{ vrf }}"
      description: "{{ vrf_descr }}"
      state: present
      validate_certs: false
    register: create_vrf
