---
- name: Create an EPG
  hosts: all
  connection: ssh
  gather_facts: no
  vars_files: ./vars.yml

  tasks:

  - name: Create an EPG
    aci_epg:
      host: "{{ apic }}"
      username: "{{ user }}"
      password: "{{ pass }}"
      tenant: "{{ tenant }}"
      ap: "{{ ap }}"
      epg: "{{ epg }}"
      bd: "{{ bd }}"
      preferred_group: yes
      state: present
      validate_certs: false
    delegate_to: localhost
