---
- name: Create a Bridge Domain
  hosts: all
  connection: ssh
  gather_facts: no
  vars_files: ./vars.yml

  tasks:

  - name: Create a BD
    aci_bd:
      host: "{{ host }}"
      username: "{{ user }}"
      password: "{{ pass }}"
      tenant: "{{ tenant }}"
      vrf: "{{ vrf }}"
      bd: "{{ bd }}"
      state: present
      validate_certs: false
    delegate_to: localhost

  - name: Create subnet for BD
    aci_bd_subnet:
      host: "{{ host }}"
      username: "{{ user }}"
      password: "{{ pass }}"
      validate_certs: false
      tenant: "{{ tenant }}"
      bd: "{{ bd }}"
      gateway: "{{ subnet }}"
      mask: "{{ mask }}"
      scope: [private, shared]
      #scope: [public, shared]
      state: present
