---
- name: Create a Vlan Pool
  hosts: all
  connection: ssh
  gather_facts: no
  vars_files: ./vars.yml

  tasks:

  - name: Create a Vlan Pool
    aci_vlan_pool:
      host: "{{ host }}"
      username: "{{ user }}"
      password: "{{ pass }}"
      pool: "{{ pool }}:{{ tenant }}-VLANPool"
      pool_allocation_mode: static
      state: present
      validate_certs: false
