---
- name: Create AEP
  hosts: all
  connection: ssh
  gather_facts: no
  vars_files: ./vars.yml

  tasks:

  - name: Create AEP
    aci_aep:
      host: "{{ host }}"
      username: "{{ user }}"
      password: "{{ pass }}"
      aep: "{{ aep }}:{{ tenant }}"
      state: present
      validate_certs: false
