---
- hosts: all
  connection: ssh
  gather_facts: no
  vars_files: ./vars.yml

  tasks:
  - name: Query tenants from ACI
    aci_tenant:
      host: "{{ host }}" 
      username: "{{ user }}"
      password: "{{ pass }}"
      state: query
      validate_certs: false
    delegate_to: localhost
    register: tenants

# Show the existent Tenants objects in JSON format
  - debug:
      msg: "{{ tenants | json_query('current[*].fvTenant.attributes.name') }}"

# Create a List of those Tenant by NAME
  - set_fact:
      sorted_tenants:  "{{ tenants | json_query('current[*].fvTenant.attributes.name') }}"

# Copy te list to a file
  - copy:
      content: "{{ sorted_tenants }}"
      dest: list_tenants.json
    delegate_to: localhost
