---
- name: Query VRFs
  hosts: all
  connection: ssh
  gather_facts: no
  vars_files: ./vars.yml

  tasks:
  - name: Query VRFs from ACI
    aci_vrf:
      host: 10.99.9.1
      username: "{{ user }}"
      password: "{{ pass }}"
      tenant: "{{ tenant }}"
      state: query
      validate_certs: false
    delegate_to: localhost
    register: vrf

  - name: Sort VRFs
    set_fact:
        sorted_vrfs: "{{ vrf.current | sort(attribute='fvCtx.attributes.name') }}"

  - copy:
      content: "{{ sorted_vrfs }}"
      dest: aci_vrfs.json
    delegate_to: localhost