---
- name: Query EPGs from a Tenant
  hosts: all
  connection: ssh
  gather_facts: no
  vars_files: ./vars.yml

  tasks:
  - name: Query EPGs from a Tenant
    aci_epg:
      host: "{{ apic }}"
      username: "{{ user }}"
      password: "{{ pass }}"
      validate_certs: no
      tenant: "{{ tenant }}"
      state: query
    register: epgs

  - copy:
      content: "{{ epgs }}"
      dest: aci_epgs.json
    delegate_to: localhost