---
- name: Query APs from ACI
  hosts: all
  connection: ssh
  gather_facts: no
  vars_files: ./vars.yml

  tasks:
  - name: Query APs from ACI
    aci_ap:
      host: "{{ apic }}"
      username: "{{ user }}"
      password: "{{ pass }}"
      validate_certs: no
      tenant: "{{ tenant }}"
      state: query
    register: aps


