---
- name: Query info from ACI
  hosts: all
  connection: ssh
  gather_facts: no
  vars_files: ./vars.yml

  tasks:
  - name: Query tenants from ACI
    aci_tenant:
      host: 10.99.9.1
      username: "{{ user }}"
      password: "{{ pass }}"
      tenant: "{{ tenant }}"
      state: query
      validate_certs: false
    register: query_result
