---

- name: Deploy Static Path binding for given EPG
  hosts: all
  connection: ssh
  gather_facts: no
  vars_files: vars.yml

  tasks:

  - name: Deploy Static Path binding for given EPG
    aci_static_binding_to_epg:
      host: "{{ host }}"
      username: "{{ user }}"
      password: "{{ pass }}"
      tenant: "{{ tenant }}"
      ap: "{{ ap }}"
      epg" "{{ epg }}"
      encap_id: "{{ vlan }}"
      deploy_immediacy: immediate
      interface_mode: access
      interface_type: switch_port
      pod_id: "{{ pod_id }}"
      leafs: "{{ node_id }}"
      interface: "{{ interface }}"
      state: present
      validate_certs: false
    register: binding
